# basler_ext_trigger_cpp_node:
#   ros__parameters:
#     exposure_time_us: 3000.0
#     trigger_source: "Line1"
#     trigger_activation: "RisingEdge"
#     trigger_mode: "On"
#     acquisition_mode: "Continuous"

#     image_topic: "/basler/image_raw"
#     frame_id: "basler_camera"

#     #mmap_path: "/dev/shm/liv_sync_ring.bin"
#     mmap_path: ""
#     lidar_mmap_path: "/dev/shm/lidar_stamp.bin"
#     #compat_stamp_path: "/dev/shm/liv_sync_stamp"
#     compat_stamp_path: ""
#     #enable_mmap: true
#     enable_mmap: false
#     lidar_mmap_timeout_ms: 500
#     mmap_size_bytes: 82008

#     reliability: "reliable"
#     queue_depth: 10

#     #match_threshold_ns: 40000000
#     match_threshold_ns: 40000
#     #resync_trigger_dt_ns: 40000000
#     resync_trigger_dt_ns: 40000
#     resync_trigger_count: 3

#     use_lidar_stamp_for_ros_header: true
#     sensor_data_qos: false
#     serial_number: ""
#     device_user_id: ""
#     load_user_set: "UserSet1"
#     publish_ros: true
#     max_images: 0
#     grab_timeout_ms: 1000
#     exposure_mode: "Timed"
#     trigger_selector: "FrameStart"
#     line_inverter: false
#     line_debouncer_us: 0.0
#     chunk_line_status_all: true
#     enforce_monotonic_lidar_seq: true

basler_ext_trigger_cpp_node:
  ros__parameters:
    exposure_time_us: 300.0
    trigger_source: "Line1"
    trigger_activation: "RisingEdge"
    trigger_mode: "On"
    acquisition_mode: "Continuous"

    image_topic: "/basler/image_raw"
    frame_id: "basler_camera"

    lidar_mmap_path: "/dev/shm/lidar_stamp.bin"
    lidar_mmap_timeout_ms: 500

    reliability: "reliable"
    queue_depth: 10

    match_threshold_ns: 80000000
    resync_trigger_dt_ns: 80000000
    resync_trigger_count: 3

    use_lidar_stamp_for_ros_header: true
    sensor_data_qos: false
    serial_number: ""
    device_user_id: ""
    load_user_set: "UserSet2"
    publish_ros: true
    max_images: 0
    grab_timeout_ms: 1000
    exposure_mode: "Timed"
    trigger_selector: "FrameStart"
    line_inverter: false
    line_debouncer_us: 0.0
    chunk_line_status_all: true
    enforce_monotonic_lidar_seq: true