<?xml version="1.0"?>
<package format="3">
  <name>basler_ext_trigger_cpp</name>
  <version>0.1.0</version>
  <description>Basler external trigger grabber for ROS 2 using pylon C++ API, shared memory ring, and optional ROS image publication.</description>
  <maintainer email="user@example.com">user</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
